ALTER TABLE dishes
RENAME COLUMN available TO is_available;

ALTER TABLE dishes
ADD COLUMN is_vegetarian BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE dishes
ADD COLUMN is_featured BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE dishes
ADD COLUMN preparation_time INTEGER NOT NULL DEFAULT 15;
